### ISSUE TITLE
xboot.bin does not work!

### ISSUE THREAD

**Issue by taonyx** [bigmagic123/d1-nezha-baremeta#1]
Hello, I had visited almost all of your documents and tried to use `xfel` to boot the `boot.bin` which under the directory `tools/windows` on my `Nezha-MQ`.
BUT IT DOES NOT WORK!
![Screenshot 2022-01-15 203319](https://user-images.githubusercontent.com/30024821/149623581-570c9de5-132c-4be7-b753-4063eebfdab8.png)
I had also tried the `rt_thread.bin` which under the same directory and it works well.
So I think maybe your image has broken, could you just test it again and then tell me the result, please.

**Comment by bigmagic123** [comment]
You are right, the current xboot.bin is only for testing whether the startup is normal, currently only for the nezha development board, if you want to develop applications based on xboot, please compile xboot yourself
